#!/usr/bin/env python3
"""
Independent per-viewport measurement of the Target.

Every number here is derived from a Target frame by the detector and the
scale fitter. Nothing is produced by evaluating the shipped responsive law --
that is the whole point: these are the observations the law is scored against,
so they must not be generated by it.

Output is Target-derived NUMBERS only, no Target pixels, so it is safe to commit.

Usage: measure-target-set.py --glob=<dir> [--glob=<dir>] --out=<json> [--hyp=both]
"""
from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent


def _load(name: str, filename: str):
    spec = importlib.util.spec_from_file_location(name, HERE / filename)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


ML = _load("measure_layout", "measure-layout.py")
FS = _load("fit_scale", "fit-scale.py")


def capture_metadata(dirs: list[Path]) -> dict:
    """Capture-side facts, so a measurement can be traced to how it was taken."""
    meta = {}
    for d in dirs:
        f = d / "capture.json"
        if not f.exists():
            continue
        payload = json.loads(f.read_text())
        for s in payload.get("samples", []):
            meta[Path(s["png"]).name] = {
                "capturedAt": payload.get("capturedAt"),
                "target": payload.get("target"),
                "viewport": [s["w"], s["h"]],
                "dpr": s.get("dpr", 1),
                "mobileEmulation": bool(s.get("mobile")),
                "touch": bool(s.get("mobile")),
                "control": s.get("control"),
                "declaredMode": s.get("mode"),
                "ready": s.get("ready"),
                "canvasBuffer": (s.get("env") or {}).get("canvasBuffer"),
                "devicePixelRatio": (s.get("env") or {}).get("devicePixelRatio"),
            }
    return meta


def structure(measure: dict, dpr: float) -> dict:
    """Row bands, row heights, gutter centres -- all in CSS pixels."""
    h = measure["size"]["h"]
    bands = [
        {"y0": b["y0"] / dpr, "y1": b["y1"] / dpr, "centre": b["center"] / dpr,
         "height": b["height"] / dpr,
         "touchesFrameEdge": bool(b["y0"] <= 0 or b["y1"] >= h - 1)}
        for b in measure["horizontalGutterBands"]
    ]
    rows = []
    for r in measure["rows"]:
        rows.append({
            "y0": r["y0"] / dpr, "y1": r["y1"] / dpr,
            "centre": (r["y0"] + r["y1"]) / 2 / dpr,
            "height": (r["y1"] - r["y0"] + 1) / dpr,
            "clipped": bool(r["clippedTop"] or r["clippedBottom"]),
            "gutterCentres": [g["center"] / dpr for g in r["verticalGutters"]],
            "gutterWidths": [g["width"] / dpr for g in r["verticalGutters"]],
            "unclippedCards": [
                {"w": c["w"] / dpr, "h": (c["h"] / dpr) if c.get("h") else None,
                 "cx": c["cx"] / dpr, "cy": (c["cy"] / dpr) if c.get("cy") else None}
                for c in r["cards"]
                if not c["clipped"]["left"] and not c["clipped"]["right"]
            ],
        })
    return {"bands": bands, "rows": rows}


def measure_one(png: Path, meta: dict, hyps: tuple[str, ...]) -> dict:
    m = ML.measure(png)
    info = meta.get(png.name, {})
    dpr = float(info.get("dpr", 1) or 1)
    w = m["size"]["w"] / dpr
    h = m["size"]["h"] / dpr
    entry = {
        "id": f"{int(round(w))}x{int(round(h))}",
        "file": png.name,
        "viewportCss": [w, h],
        "orientation": "portrait" if w < h else ("square" if w == h else "landscape"),
        "aspect": round(w / h, 5),
        "capture": info,
        "voidPreset": m["voidMask"]["mode"],
        "structure": structure(m, dpr),
        "fits": {},
    }
    for hyp in hyps:
        r = FS.fit_one(m, hyp)
        if "scale" in r:
            # fit-scale works in the frame's own pixels; normalise to CSS.
            r["scale"] = round(r["scale"] / dpr, 6)
            r["scrollX"] = round(r["scrollX"], 3)
            r["scrollY"] = round(r["scrollY"], 3)
            r["rmsPx"] = round(r["rmsPx"] / dpr, 3)
            r["maxPx"] = round(r["maxPx"] / dpr, 3)
        entry["fits"][hyp] = r
    return entry


if __name__ == "__main__":
    args = sys.argv[1:]
    globs = [Path(a.split("=", 1)[1]) for a in args if a.startswith("--glob=")]
    out = next((a.split("=", 1)[1] for a in args if a.startswith("--out=")), "qa-v5/f2/target-measurements.json")
    hyp = next((a.split("=", 1)[1] for a in args if a.startswith("--hyp=")), "both")
    only = next((a.split("=", 1)[1] for a in args if a.startswith("--only=")), None)
    hyps = ("camera", "focal") if hyp == "both" else (hyp,)

    meta = capture_metadata(globs)
    pngs = sorted(p for g in globs for p in g.glob("*.png"))
    if only:
        wanted = set(only.split(","))
        pngs = [p for p in pngs if any(p.name.startswith(w) for w in wanted)]

    results = []
    for png in pngs:
        entry = measure_one(png, meta, hyps)
        results.append(entry)
        f = entry["fits"].get("focal") or next(iter(entry["fits"].values()), {})
        bands = [b for b in entry["structure"]["bands"] if not b["touchesFrameEdge"]]
        print(f"{entry['id']:>10} {entry['orientation']:<9} "
              f"S={f.get('scale', float('nan')):.5f} rms={f.get('rmsPx', float('nan')):6.2f} "
              f"bands={len(bands)} rows={len(entry['structure']['rows'])}", flush=True)

    payload = {
        "note": "Independent Target measurements. No value here is produced by "
                "evaluating the shipped responsive law.",
        "detector": "scripts/v5/measure-layout.py",
        "fitter": "scripts/v5/fit-scale.py",
        "targetPixelPolicy": "numbers only; no Target pixels are stored in this file",
        "viewports": results,
    }
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_text(json.dumps(payload, indent=2))
    print(f"wrote {out} ({len(results)} viewports)")
