import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const LOCAL = "http://127.0.0.1:5280";

function run(cmd, args) {
  return new Promise((resolve) => {
    const child = spawn(cmd, args, { cwd: ROOT, stdio: "inherit" });
    child.on("close", (code) => resolve(code ?? 1));
  });
}

async function localUp() {
  try {
    const res = await fetch(LOCAL, { signal: AbortSignal.timeout(2000) });
    return res.ok;
  } catch {
    return false;
  }
}

const started = new Date().toISOString();
const up = await localUp();
const results = [];

if (!up) {
  results.push({ name: "local-server", status: "blocked", detail: `${LOCAL} not reachable` });
} else {
  for (const name of ["test:visual", "test:interaction", "test:performance", "test:responsive"]) {
    const code = await run("npm", ["run", name]);
    results.push({ name, status: code === 0 ? "passed" : "failed", code });
  }
}

const hasBlocker = results.some((item) => item.status === "blocked" || item.status === "failed");
const report = `# Final QA

Date: ${started}
Local: ${LOCAL}
Reference: https://infinite-liquid-glass.shader.se/?v=2

## Commands

${results.map((item) => `- ${item.name}: ${item.status}`).join("\n")}

## Scoring notes

Independent auditor (Agent 2) must rescore. This file is generated by the implementation tree and is not a pass by itself.

Known remaining differences at generation time:

- Tile interiors use original generated plates, not Mux videos (authorization).
- Footer wordmark is a placeholder (ATELIER), not the origin brand file.
- Fonts are official Geist Variable, not the origin-hosted woff2 files.
- HDRI is a generated studio env, not the origin-hosted \`studio_small_03_1k.hdr\`.
- Named comparison videos / SSIM gates may still be incomplete.

## Defects

P0/P1/P2 must be filled by the independent auditor after recapture.

## Score

Not independently scored in this command.

${hasBlocker ? "final result: blocked" : "final result: blocked"}
`;

fs.mkdirSync(path.join(ROOT, "qa"), { recursive: true });
fs.writeFileSync(path.join(ROOT, "qa", "final-qa.md"), report);
console.log(report);
process.exit(hasBlocker ? 1 : 0);
